require('plugins')
require('settings')
require('keymappings')
require("filetypes")
require('pl-treesitter')
require('pl-lspconfig')
require('pl-lspinstall')
require('pl-compe')
require('pl-tree')
require("pl-autopairs")
require("pl-telescope")
require("pl-galaxyline")
require('colorscheme')

